version: '3'

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - TZ=Europe/Paris
    volumes:
      - /etc/deluge:/config
      - /mnt/usb/mediaserver:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped

